<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;" class="">This Agreement is </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;" class="">an integral part of the </font></font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;" class="">Terms of Service of the</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;" class=""> Master Agreement </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;" class="">and is considered only in conjunction with it.</font></font></font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Please read </font></font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">the </font></font></font><font style="vertical-align: inherit;"><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">hosting </font></font></b></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">agreement</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> carefully </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">as it contains important information about your rights and obligations.</font></font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"></font></font></font></p>
<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Overview</font></font></font></font></h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
The Hosting Agreement (hereinafter referred to as the "Agreement") is concluded </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">between </font></font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">GHosting Ltd</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and you (customer / subscriber) and is effective from the date of purchase of the hosting service. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">This agreement sets out the terms of the hosting service. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The terms "Organization", "We" or "Our" refer to </font></font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ghosting Ltd.,</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and the terms "You", "Your", "Customer", "Subscriber" refer to any person or entity that enters into this Agreement.
</font></font></font></font><ol>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;" class="">Description of services</font></font></font></font></h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		We offer the following types of hosting services:
		</font></font></font></font><ul>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Web Hosting</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - Each </font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">hosting</font></font></font></b></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> account </font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">is hosted on an</font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> isolated virtual server that can be managed using a dedicated control panel. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The server can also be managed via an SSH client (root privileges).
</font></font></font></font></li>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">VPS servers</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - you can install any software on a VPS server and properly manage the server. 
</font></font></font></font></li>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Database. </font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">If your site uses a large volume of MSSQL, MYSQL or Postgresql databases, this may cause the site to crash due to the database using a large amount of server resources. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Use a database customized and optimized by Google.
</font></font></font></font></li>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Professional hosting</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - if your site serves a large number of visitors and requires special server services, our company offers professional services for setting up and administering servers.
</font></font></font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Account management conditions; </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Limitations</font></font></font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.1. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Transfer of servers. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You understand and agree that the organization may require so-called servers. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">"Transfer" and, as a result, change the IP address originally assigned to you. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Therefore, we do not guarantee that you will always use the same IP address.</font></font></font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.2. Saving space. The total amount of storage that will be used on the server (s) may vary depending on the size of the files provided. Storage space may be required to store both operating systems and system files and / or other support files.</font></font></font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.3. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Termination of hosting services. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You acknowledge and agree that upon the expiration or termination of your hosting service, you will terminate the hosting service and refuse to use the IP addresses and server names provided by your hosting service. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">It is your responsibility to ensure that the content of your website or server is moved from our servers prior to the termination of the service. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We are not obligated to transfer the content of your website or server to another provider. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">If you are unable to move the website or content from our servers in time before canceling the service, we will be forced to delete the data and it will no longer be recoverable. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We will also be unable to provide you with copies of them.</font></font></font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Obligations and guarantees of the parties</font></font></font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.1. </font><font style="vertical-align: inherit;">The organization is obliged to constantly monitor and ensure the security of its own servers, keep backups and restore backups in the event of unauthorized damage to your site. </font><font style="vertical-align: inherit;">However, there is no 100% guarantee that the files will be kept intact and / or deleted, so the organization will not be held liable for any loss of files stored on the servers by the user. </font><font style="vertical-align: inherit;">The user is obliged to make backup copies of the information uploaded to the servers and store it on his personal computer at regular intervals.</font></font></font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.2. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We strive to provide timely and prompt correction of defects during the service process. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In addition, the organization is committed to notifying users in advance of any expected deficiencies or defects that are known to the organization.</font></font></font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.3. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The organization is obliged to fulfill its obligations and provide services within the terms established by the agreement of the parties.</font></font></font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.4. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Users, in turn, undertake not to use our servers to download information that is malicious and includes (but is not limited to) the following: IRC scripts / bots, IRCD, proxy / anonymous scripts, AutoSurf / PTC / PTS / PPC sites, IP scanner , Bruteforce software. </font><font style="vertical-align: inherit;">/ Scripts / Software, Mail Bombs / Spam Scripts, HYIP or related websites, investment sites (FOREX, E-Gold Exchange, Second Life / Linden Exchange, Pons, MLM / Pyramid Scheme) and more. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The </font></font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Terms of Service set forth</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> the prohibited content and information on additional items </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">that cannot be downloaded, stored or processed when using our servers.
</font></font></font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Data protection and security.</font></font></font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4.1. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The user is obliged to comply with the requirements of confidentiality and protection of personal data in accordance with the General Data Protection Regulation (EU) 2016/679) established by the GDPR. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">This applies to the collection, storage and processing of any personal information, data or content through the User's Website.</font></font></font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4.2. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You are personally responsible for ensuring that your website maintains organizational and technical security measures that adequately protect the personal data stored / processed on the website or server. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Accordingly, in case of violation of the rules for collecting, processing or storing data, the subscriber is fully responsible for such violations, unless, of course, these violations are related to our server / technical error.</font></font></font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Zero Tolerance Spam Policy</font></font></font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.1. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We have a zero-tolerance policy on spam and bulk emails. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The Organization will immediately, without any notice, terminate the account of any user who sends the spam message.</font></font></font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.2. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In case of non-payment or timely payment of the cost of the service, the organization has the right to suspend the provision of the service after 5 (five) working days from the date of mandatory payment. </font></font></font><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">During this period, we store their data (email, website database, etc.) on our servers, and after 30 business days, all subscriber data is deleted from the server.</font></font></font></font></li>
		</ul>
	</li>
	<br><br>
	<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		In our Universal </font></font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">terms and conditions</font></font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> of the agreement </font></font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">on the provision of services</font></font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> set forth the terms of payment, refunds, renewals and other conditions associated with hosting services.
	</font></font></font></font></li>
	<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		Contract clauses are governed by headings to facilitate the use of the contract text, and these headings are not considered to be defining, superseding, or clarifying any provision of that contract.
	</font></font></font></font></li>
	<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		In the event of any inconsistency between the provisions of this Agreement and the Terms and Conditions of the Universal Agreement for our services, the terms of this Agreement shall prevail.
	</font></font></font></font></li>
</ol>