<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Настоящее Соглашение является </font><font style="vertical-align: inherit;">неотъемлемой частью </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Условий предоставления услуг</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Основного соглашения </font><font style="vertical-align: inherit;">и рассматривается только вместе с ним.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Пожалуйста, внимательно прочтите </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">соглашение</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> о </font><b><font style="vertical-align: inherit;">хостинге,</font></b><font style="vertical-align: inherit;"> поскольку оно содержит важную информацию о ваших правах и обязанностях.</font></font></p>
<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Обзор</font></font></h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
Соглашение о хостинге (далее именуемое «Соглашение») заключается </font><font style="vertical-align: inherit;">между </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">GHosting Ltd</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> и вами (клиентом / подписчиком) и вступает в силу с даты приобретения услуги хостинга. </font><font style="vertical-align: inherit;">В этом соглашении изложены условия предоставления услуг хостинга. </font><font style="vertical-align: inherit;">Термины «Организация», «Мы» или «Наш» относятся к </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ghosting Ltd.,</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> а термины «Вы», «Ваш», «Клиент», «Подписчик» относятся к любому физическому или юридическому лицу, которое вступает в настоящее Соглашение.
</font></font><ol>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Описание услуг</font></font></h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		Мы предлагаем следующие виды услуг хостинга:
		</font></font><ul>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Веб-хостинг</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - каждая учетная запись хостинга </font><b><font style="vertical-align: inherit;">размещается на</font></b><font style="vertical-align: inherit;"> изолированном виртуальном сервере, которым можно управлять с помощью специальной панели управления. </font><font style="vertical-align: inherit;">Сервером также можно управлять через SSH-клиент (привилегии root).
</font></font></li>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">VPS-серверы</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - на VPS-сервер можно установить любое программное обеспечение и правильно управлять сервером. 
</font></font></li>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Базы данных.</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Если на вашем сайте используется большой объем баз данных MSSQL, MYSQL или Postgresql, это может привести к сбою в работе сайта из-за того, что база данных использует большой объем ресурсов сервера. </font><font style="vertical-align: inherit;">Используйте базу данных, настроенную и оптимизированную специалистами Google.
</font></font></li>
			<li><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Профессиональный хостинг</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - если ваш сайт обслуживает большое количество посетителей и требует специальных серверных услуг, наша компания предлагает профессиональные услуги по настройке и администрированию серверов.
</font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Условия ведения счета; </font><font style="vertical-align: inherit;">Ограничения</font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.1. </font><font style="vertical-align: inherit;">Перенос серверов. </font><font style="vertical-align: inherit;">Вы понимаете и соглашаетесь с тем, что организации могут потребоваться так называемые серверы. </font><font style="vertical-align: inherit;">«Перенести» и, как следствие, изменить изначально назначенный вам IP-адрес. </font><font style="vertical-align: inherit;">Поэтому мы не гарантируем, что вы всегда будете использовать один и тот же IP-адрес.</font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.2. Экономия места. Общий объем хранилища, который будет использоваться на сервере (ах), может варьироваться в зависимости от размера представленных файлов. Место для хранения может потребоваться для хранения как операционных систем, так и системных файлов и / или других вспомогательных файлов.</font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.3. </font><font style="vertical-align: inherit;">Прекращение предоставления услуг хостинга. </font><font style="vertical-align: inherit;">Вы признаете и соглашаетесь с тем, что по истечении срока действия или прекращения вашей услуги хостинга вы прекратите предоставление услуги хостинга и откажетесь использовать IP-адреса и имена серверов, предоставленные вашей услугой хостинга. </font><font style="vertical-align: inherit;">Вы несете ответственность за то, чтобы содержимое вашего веб-сайта или сервера было перемещено с наших серверов до прекращения обслуживания. </font><font style="vertical-align: inherit;">Мы не обязаны передавать содержимое вашего веб-сайта или сервера другому провайдеру. </font><font style="vertical-align: inherit;">Если вы не можете переместить веб-сайт или контент с наших серверов вовремя до отмены услуги, мы будем вынуждены удалить данные, и они больше не будут подлежать восстановлению. </font><font style="vertical-align: inherit;">Мы также будем лишены возможности предоставить вам их копии.</font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Обязанности и гарантии сторон</font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.1. Организация обязана постоянно контролировать и обеспечивать безопасность собственных серверов, хранить резервные копии и восстанавливать резервные копии в случае несанкционированного повреждения вашего сайта. Однако нет 100% гарантии того, что файлы будут сохранены без изменений и / или будут удалены, поэтому организация не будет нести ответственность за любую потерю файлов, хранящихся на серверах пользователем. Пользователь обязан делать резервные копии информации, загружаемой на серверы, и сохранять ее на своем персональном компьютере через определенные промежутки времени.</font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.2. </font><font style="vertical-align: inherit;">Мы стремимся обеспечить своевременное и скорейшее исправление дефектов в процессе обслуживания. </font><font style="vertical-align: inherit;">Кроме того, организация обязуется заранее уведомлять пользователей о любых ожидаемых недостатках или дефектах, которые известны организации.</font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.3. </font><font style="vertical-align: inherit;">Организация обязана выполнять взятые на себя обязательства и оказывать услуги в сроки, установленные соглашением сторон.</font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3.4. </font><font style="vertical-align: inherit;">Пользователи, в свою очередь, обязуются не использовать наши серверы для загрузки информации, которая является вредоносной и включает (но не ограничивается) следующее: сценарии / боты IRC, IRCD, сценарии прокси / анонимные, сайты AutoSurf / PTC / PTS / PPC, сканер IP, программное обеспечение Bruteforce. / Scripts / Software, Mail Bombs / Spam Scripts, HYIP или связанные веб-сайты, инвестиционные сайты (FOREX, E-Gold Exchange, Second Life / Linden Exchange, Pons, MLM / Pyramid Scheme) и многое другое. </font><font style="vertical-align: inherit;">В </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Условии предоставления услуг изложено в</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> содержании запрещенного и информация о дополнительных предметах , </font><font style="vertical-align: inherit;">которые не могут быть загружены, хранятся или обрабатываются при использовании наших серверов.
</font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Защита и безопасность данных.</font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4.1. </font><font style="vertical-align: inherit;">Пользователь обязан соблюдать требования конфиденциальности и защиты персональных данных в соответствии с Общим регламентом о защите данных (ЕС) 2016/679), установленным GDPR. </font><font style="vertical-align: inherit;">Это относится к сбору, хранению и обработке любой личной информации, данных или контента через Веб-сайт пользователя.</font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4.2. </font><font style="vertical-align: inherit;">Вы несете личную ответственность за обеспечение того, чтобы ваш веб-сайт поддерживал организационные и технические меры безопасности, которые адекватно защищают личные данные, хранящиеся / обрабатываемые на веб-сайте или на сервере. </font><font style="vertical-align: inherit;">Соответственно, в случае нарушения правил сбора, обработки или хранения данных, подписчик несет полную ответственность за такие нарушения, если, конечно, эти нарушения не связаны с нашим сервером / технической ошибкой.</font></font></li>
		</ul>
	</li>
	<li>
		<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Политика абсолютной нетерпимости к спаму</font></font></h4>
		<ul>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.1. </font><font style="vertical-align: inherit;">У нас есть политика абсолютной нетерпимости к спаму и массовым рассылкам. </font><font style="vertical-align: inherit;">Организация немедленно, без какого-либо уведомления, аннулирует учетную запись любого пользователя, который отправляет спам-сообщение.</font></font></li>
			<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.2. </font><font style="vertical-align: inherit;">В случае неуплаты или своевременной оплаты стоимости услуги, организация имеет право приостановить оказание услуги по истечении 5 (пяти) рабочих дней с даты обязательной оплаты. </font><font style="vertical-align: inherit;">В течение этого периода мы храним его данные (электронную почту, базу данных веб-сайта и т. Д.) На наших серверах, а через 30 рабочих дней все данные подписчика удаляются с сервера.</font></font></li>
		</ul>
	</li>
	<br><br>
	<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		В наших Универсальных </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">условиях и положениях</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> соглашения </font><b><font style="vertical-align: inherit;">о предоставлении услуг</font></b><font style="vertical-align: inherit;"> изложены условия оплаты, возмещения, продления и другие условия, связанные с услугами хостинга.
	</font></font></li>
	<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		Статьи контракта руководствуются заголовками, чтобы облегчить использование текста контракта, и эти заголовки не считаются определяющими, заменяющими или разъясняющими какое-либо положение этого контракта.
	</font></font></li>
	<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
		В случае любого несоответствия между положениями настоящего Соглашения и Положениями и условиями Универсального соглашения о наших услугах, условия настоящего Соглашения имеют преимущественную силу.
	</font></font></li>
</ol>